name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build . -t abhishek976772/demo-app1

    - name: Log in to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Push Docker image
      run: docker push abhishek976772/demo-app1:latest
      
    - name: Install semantic-release
      run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm

    - name: Run semantic-release
      run: npx semantic-release
